-- =============================================================
-- RG Family: 고객사 Supabase 마이그레이션용 통합 스키마
-- 생성일: 2026-03-25
--
-- 사용법: 고객사 Supabase Dashboard > SQL Editor에서 실행
-- ⚠️ 새 프로젝트(빈 DB)에서 실행하세요!
-- =============================================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================
-- PART 1: ENUM 타입
-- =============================================================

DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('member', 'bj', 'vip', 'moderator', 'admin', 'superadmin');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.org_unit AS ENUM ('excel', 'crew');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- =============================================================
-- PART 2: 테이블 생성 (30개)
-- =============================================================

-- 1. Profiles (회원 프로필)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
  nickname text NOT NULL,
  email text,
  avatar_url text,
  role public.user_role DEFAULT 'member'::public.user_role NOT NULL,
  unit public.org_unit,
  total_donation bigint DEFAULT 0,
  pandatv_id text,
  account_type text DEFAULT 'real' CHECK (account_type IN ('real', 'virtual', 'system')),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 2. Seasons (시즌)
CREATE TABLE IF NOT EXISTS public.seasons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  start_date date NOT NULL,
  end_date date,
  is_active boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 3. BJ 직급 마스터
CREATE TABLE IF NOT EXISTS public.bj_ranks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  level integer NOT NULL,
  display_order integer DEFAULT 0,
  color text,
  emoji text,
  tier text,
  icon_url text,
  description text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 4. Organization (조직도 - BJ 마스터 프로필)
CREATE TABLE IF NOT EXISTS public.organization (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit public.org_unit NOT NULL,
  profile_id uuid REFERENCES public.profiles(id),
  name text NOT NULL,
  role text NOT NULL,
  position_order int DEFAULT 0 NOT NULL,
  parent_id bigint REFERENCES public.organization(id),
  image_url text,
  social_links jsonb,
  profile_info jsonb,
  is_live boolean DEFAULT false NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  current_rank text,
  current_rank_id bigint REFERENCES public.bj_ranks(id),
  total_contribution integer DEFAULT 0,
  season_contribution integer DEFAULT 0,
  total_prize integer DEFAULT 0,
  total_penalty integer DEFAULT 0,
  prize_balance integer DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 5. Episodes (에피소드/직급전)
CREATE TABLE IF NOT EXISTS public.episodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  episode_number integer NOT NULL,
  title text NOT NULL,
  broadcast_date date NOT NULL,
  is_rank_battle boolean DEFAULT false NOT NULL,
  description text,
  is_finalized boolean DEFAULT false NOT NULL,
  finalized_at timestamptz,
  source_file text,
  total_hearts bigint DEFAULT 0,
  donor_count integer DEFAULT 0,
  unit public.org_unit DEFAULT 'excel',
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 6. Donations (후원 내역)
CREATE TABLE IF NOT EXISTS public.donations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  amount bigint NOT NULL,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  episode_id bigint REFERENCES public.episodes(id),
  unit public.org_unit,
  target_bj text,
  donated_at timestamptz,
  member_name text,
  heart_score bigint,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 7. VIP Rewards (VIP 보상)
CREATE TABLE IF NOT EXISTS public.vip_rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid REFERENCES public.profiles(id) NOT NULL,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  episode_id bigint REFERENCES public.episodes(id),
  rank int NOT NULL,
  personal_message text,
  dedication_video_url text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 8. VIP Images
CREATE TABLE IF NOT EXISTS public.vip_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reward_id bigint REFERENCES public.vip_rewards(id) ON DELETE CASCADE NOT NULL,
  image_url text NOT NULL,
  title text,
  order_index int DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 9. Signatures (시그니처)
CREATE TABLE IF NOT EXISTS public.signatures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sig_number integer NOT NULL,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  unit public.org_unit NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT signatures_unit_sig_number_unique UNIQUE (unit, sig_number)
);

-- 10. Signature Videos (시그 영상)
CREATE TABLE IF NOT EXISTS public.signature_videos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signature_id bigint NOT NULL REFERENCES public.signatures(id) ON DELETE CASCADE,
  member_id bigint NOT NULL REFERENCES public.organization(id) ON DELETE CASCADE,
  video_url text NOT NULL,
  cloudflare_uid text,
  is_published boolean DEFAULT true,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT signature_videos_sig_member_unique UNIQUE (signature_id, member_id)
);

-- 11. Schedules (일정)
CREATE TABLE IF NOT EXISTS public.schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  unit public.org_unit,
  event_type text CHECK (event_type IN ('broadcast', 'collab', 'event', 'notice', '休')) NOT NULL,
  start_datetime timestamptz NOT NULL,
  end_datetime timestamptz,
  location text,
  is_all_day boolean DEFAULT false NOT NULL,
  color text,
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 12. Timeline Events
CREATE TABLE IF NOT EXISTS public.timeline_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_date date NOT NULL,
  title text NOT NULL,
  description text,
  image_url text,
  category text,
  season_id bigint REFERENCES public.seasons(id),
  order_index int DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 13. Notices (공지사항)
CREATE TABLE IF NOT EXISTS public.notices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  category text CHECK (category IN ('official', 'excel', 'crew')) NOT NULL,
  thumbnail_url text,
  is_pinned boolean DEFAULT false NOT NULL,
  view_count bigint DEFAULT 0 NOT NULL,
  author_id uuid REFERENCES public.profiles(id),
  display_order integer,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 14. Notice Attachments (공지 첨부파일)
CREATE TABLE IF NOT EXISTS public.notice_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id bigint NOT NULL REFERENCES public.notices(id) ON DELETE CASCADE,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_type text CHECK (file_type IN ('image', 'video')) NOT NULL,
  file_size bigint,
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 15. Posts (게시글)
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_type text CHECK (board_type IN ('free', 'vip')) NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  author_id uuid REFERENCES public.profiles(id) NOT NULL,
  view_count bigint DEFAULT 0 NOT NULL,
  like_count bigint DEFAULT 0 NOT NULL,
  comment_count bigint DEFAULT 0 NOT NULL,
  is_anonymous boolean DEFAULT false NOT NULL,
  is_deleted boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 16. Comments (댓글)
CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  author_id uuid REFERENCES public.profiles(id) NOT NULL,
  content text NOT NULL,
  parent_id bigint REFERENCES public.comments(id),
  is_anonymous boolean DEFAULT false NOT NULL,
  is_deleted boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 17. Post Likes (좋아요)
CREATE TABLE IF NOT EXISTS public.post_likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT post_likes_unique UNIQUE (post_id, user_id)
);

-- 18. Media Content (Shorts/VOD)
CREATE TABLE IF NOT EXISTS public.media_content (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text CHECK (content_type IN ('shorts', 'vod')) NOT NULL,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  video_url text NOT NULL,
  cloudflare_uid text,
  unit public.org_unit,
  duration int,
  view_count bigint DEFAULT 0 NOT NULL,
  is_featured boolean DEFAULT false NOT NULL,
  is_published boolean DEFAULT true,
  parent_id bigint,
  part_number integer DEFAULT 1,
  total_parts integer DEFAULT 1,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 19. Live Status
CREATE TABLE IF NOT EXISTS public.live_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint REFERENCES public.organization(id) NOT NULL,
  platform text CHECK (platform IN ('chzzk', 'twitch', 'youtube', 'pandatv')) NOT NULL,
  stream_url text NOT NULL,
  thumbnail_url text,
  is_live boolean DEFAULT false NOT NULL,
  viewer_count int DEFAULT 0 NOT NULL,
  last_checked timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT live_status_member_platform_unique UNIQUE (member_id, platform)
);

-- 20. Banners
CREATE TABLE IF NOT EXISTS public.banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  image_url text NOT NULL,
  link_url text,
  display_order int DEFAULT 0 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 21. Tribute Guestbook (방명록)
CREATE TABLE IF NOT EXISTS public.tribute_guestbook (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tribute_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  author_name text NOT NULL,
  message text NOT NULL CHECK (char_length(message) <= 500),
  is_member boolean DEFAULT FALSE,
  is_approved boolean DEFAULT TRUE,
  is_deleted boolean DEFAULT FALSE,
  created_at timestamptz DEFAULT NOW() NOT NULL,
  updated_at timestamptz DEFAULT NOW() NOT NULL
);

-- 22. BJ Thank You Messages
CREATE TABLE IF NOT EXISTS public.bj_thank_you_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vip_profile_id uuid NOT NULL REFERENCES public.profiles(id),
  bj_member_id bigint NOT NULL REFERENCES public.organization(id),
  message_type text CHECK (message_type IN ('text', 'image', 'video')) NOT NULL,
  content_text text,
  content_url text,
  is_public boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 23. VIP Personal Messages
CREATE TABLE IF NOT EXISTS public.vip_personal_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vip_profile_id uuid NOT NULL REFERENCES public.profiles(id),
  author_id uuid NOT NULL REFERENCES public.profiles(id),
  message_type text CHECK (message_type IN ('text', 'image', 'video')) DEFAULT 'text',
  content_text text,
  content_url text,
  is_public boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 24. VIP Message Comments
CREATE TABLE IF NOT EXISTS public.vip_message_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint NOT NULL REFERENCES public.vip_personal_messages(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES public.profiles(id),
  content text NOT NULL,
  parent_id bigint REFERENCES public.vip_message_comments(id),
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 25. Rank Battle Records (명예의 전당)
CREATE TABLE IF NOT EXISTS public.rank_battle_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  battle_number integer NOT NULL,
  rank integer NOT NULL,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  total_amount bigint NOT NULL,
  finalized_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT rank_battle_records_unique UNIQUE (season_id, battle_number, rank)
);

-- 26. Total Donation Rankings (역대 누적 Top 50)
CREATE TABLE IF NOT EXISTS public.total_donation_rankings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rank integer NOT NULL UNIQUE,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  total_amount bigint NOT NULL,
  donation_count integer DEFAULT 0,
  top_bj text,
  is_permanent_vip boolean DEFAULT false,
  avatar_url text
);

-- 27. Season Donation Rankings (시즌별 Top 50)
CREATE TABLE IF NOT EXISTS public.season_donation_rankings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  rank integer NOT NULL,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  total_amount bigint NOT NULL,
  donation_count integer DEFAULT 0,
  top_bj text,
  unit public.org_unit,
  avatar_url text,
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT season_donation_rankings_unique UNIQUE (season_id, rank)
);

-- 28. Signature Eligibility (시그니처 자격)
CREATE TABLE IF NOT EXISTS public.signature_eligibility (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  sig_number integer NOT NULL,
  episode_id bigint REFERENCES public.episodes(id),
  episode_number integer,
  daily_amount bigint NOT NULL,
  threshold_amount bigint NOT NULL,
  earned_at timestamptz,
  is_claimed boolean DEFAULT false,
  claimed_at timestamptz,
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 29. Season Members (시즌별 멤버 구성)
CREATE TABLE IF NOT EXISTS public.season_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint NOT NULL REFERENCES public.seasons(id),
  member_id bigint NOT NULL REFERENCES public.organization(id),
  unit public.org_unit NOT NULL,
  role text DEFAULT 'member',
  position_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  joined_at timestamptz DEFAULT now(),
  left_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT season_members_unique UNIQUE (season_id, member_id)
);

-- 30. Contribution Logs (기여도 변동 로그)
CREATE TABLE IF NOT EXISTS public.contribution_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bj_member_id bigint NOT NULL REFERENCES public.organization(id),
  episode_id bigint REFERENCES public.episodes(id),
  season_id bigint REFERENCES public.seasons(id),
  amount integer NOT NULL,
  reason text NOT NULL,
  balance_after integer DEFAULT 0,
  event_type text,
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 31. Prize Penalties (상벌금)
CREATE TABLE IF NOT EXISTS public.prize_penalties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bj_member_id bigint NOT NULL REFERENCES public.organization(id),
  episode_id bigint REFERENCES public.episodes(id),
  season_id bigint REFERENCES public.seasons(id),
  type text CHECK (type IN ('prize', 'penalty')) NOT NULL,
  amount integer NOT NULL,
  description text,
  is_paid boolean DEFAULT false,
  paid_at timestamptz,
  payment_note text,
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 32. BJ Rank History (직급 변동 이력)
CREATE TABLE IF NOT EXISTS public.bj_rank_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bj_member_id bigint NOT NULL REFERENCES public.organization(id),
  episode_id bigint REFERENCES public.episodes(id),
  season_id bigint REFERENCES public.seasons(id),
  rank_id bigint NOT NULL REFERENCES public.bj_ranks(id),
  previous_rank_id bigint REFERENCES public.bj_ranks(id),
  change_reason text,
  is_rank_battle boolean DEFAULT false,
  battle_number integer,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 33. BJ Episode Performances (에피소드별 성적)
CREATE TABLE IF NOT EXISTS public.bj_episode_performances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id bigint NOT NULL REFERENCES public.episodes(id),
  bj_member_id bigint NOT NULL REFERENCES public.organization(id),
  donation_hearts bigint DEFAULT 0,
  donation_count integer DEFAULT 0,
  heart_score bigint DEFAULT 0,
  contribution integer DEFAULT 0,
  final_rank integer,
  rank_result text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT bj_episode_perf_unique UNIQUE (episode_id, bj_member_id)
);

-- =============================================================
-- PART 3: Views (보안 뷰)
-- =============================================================

-- Total Rankings Public (시청자 점수 변환, total_amount 숨김)
CREATE OR REPLACE VIEW public.total_rankings_public AS
SELECT
  tdr.id,
  tdr.rank,
  tdr.donor_name,
  (tdr.total_amount * 50) AS viewer_score,
  tdr.donation_count,
  tdr.top_bj,
  tdr.donor_id AS profile_id,
  tdr.avatar_url,
  CASE
    WHEN p.id IS NOT NULL
      AND p.avatar_url IS NOT NULL
      AND EXISTS (
        SELECT 1 FROM public.vip_personal_messages vpm
        WHERE vpm.vip_profile_id = p.id AND vpm.is_public = true AND vpm.is_deleted = false
      )
    THEN true
    ELSE false
  END AS is_vip_clickable
FROM public.total_donation_rankings tdr
LEFT JOIN public.profiles p ON tdr.donor_id = p.id;

-- Season Rankings Public
CREATE OR REPLACE VIEW public.season_rankings_public AS
SELECT
  sdr.id,
  sdr.season_id,
  sdr.rank,
  sdr.donor_name,
  (sdr.total_amount * 50) AS viewer_score,
  sdr.donation_count,
  sdr.unit::text,
  sdr.top_bj,
  sdr.donor_id AS profile_id,
  sdr.avatar_url,
  CASE
    WHEN p.id IS NOT NULL
      AND p.avatar_url IS NOT NULL
      AND EXISTS (
        SELECT 1 FROM public.vip_personal_messages vpm
        WHERE vpm.vip_profile_id = p.id AND vpm.is_public = true AND vpm.is_deleted = false
      )
    THEN true
    ELSE false
  END AS is_vip_clickable,
  sdr.updated_at,
  sdr.created_at
FROM public.season_donation_rankings sdr
LEFT JOIN public.profiles p ON sdr.donor_id = p.id;

-- VIP Clickable Profiles
CREATE OR REPLACE VIEW public.vip_clickable_profiles AS
SELECT
  p.id AS profile_id,
  p.nickname,
  p.avatar_url,
  CASE
    WHEN p.avatar_url IS NOT NULL
      AND EXISTS (
        SELECT 1 FROM public.vip_personal_messages vpm
        WHERE vpm.vip_profile_id = p.id AND vpm.is_public = true AND vpm.is_deleted = false
      )
    THEN true
    ELSE false
  END AS is_vip_clickable
FROM public.profiles p;

-- =============================================================
-- PART 4: 트리거 및 함수
-- =============================================================

-- 회원가입 시 profiles 자동 생성
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, nickname, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nickname', split_part(NEW.email, '@', 1)),
    NEW.email,
    'member'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- updated_at 자동 업데이트
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger AS $$
BEGIN
  new.updated_at = now();
  return new;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS handle_updated_at ON public.profiles;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.notices;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.notices
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.posts;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.posts
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.banners;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.banners
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.tribute_guestbook;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.tribute_guestbook
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.prize_penalties;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.prize_penalties
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- =============================================================
-- PART 5: 헬퍼 함수 (RPC)
-- =============================================================

-- Admin 체크
CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.profiles
    WHERE id = user_id AND role IN ('admin', 'superadmin')
  );
$$;

-- Staff 체크 (moderator 포함)
CREATE OR REPLACE FUNCTION public.is_staff(user_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.profiles
    WHERE id = user_id AND role IN ('moderator', 'admin', 'superadmin')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN RETURN public.is_admin(auth.uid()); END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_moderator()
RETURNS boolean AS $$
BEGIN RETURN public.is_staff(auth.uid()); END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 활성 시즌 ID
CREATE OR REPLACE FUNCTION public.get_active_season_id()
RETURNS bigint LANGUAGE sql STABLE AS $$
  SELECT id FROM public.seasons WHERE is_active = true
  ORDER BY start_date DESC NULLS LAST LIMIT 1;
$$;

-- 사용자 랭킹
CREATE OR REPLACE FUNCTION public.get_user_rank(
  p_user_id uuid, p_season_id bigint DEFAULT NULL
)
RETURNS TABLE(rank integer, total_amount bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF p_user_id IS NULL THEN RETURN; END IF;
  IF p_season_id IS NULL THEN
    RETURN QUERY
      WITH totals AS (
        SELECT donor_id, sum(amount)::bigint AS total_amount,
               dense_rank() OVER (ORDER BY sum(amount) DESC) AS rank
        FROM public.donations WHERE donor_id IS NOT NULL GROUP BY donor_id
      )
      SELECT totals.rank::integer, totals.total_amount FROM totals WHERE totals.donor_id = p_user_id;
  ELSE
    RETURN QUERY
      WITH totals AS (
        SELECT donor_id, sum(amount)::bigint AS total_amount,
               dense_rank() OVER (ORDER BY sum(amount) DESC) AS rank
        FROM public.donations WHERE donor_id IS NOT NULL AND season_id = p_season_id GROUP BY donor_id
      )
      SELECT totals.rank::integer, totals.total_amount FROM totals WHERE totals.donor_id = p_user_id;
  END IF;
END;
$$;

-- 활성 시즌 랭킹
CREATE OR REPLACE FUNCTION public.get_user_rank_active_season(p_user_id uuid)
RETURNS TABLE(rank integer, total_amount bigint, season_id bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_season_id bigint;
BEGIN
  SELECT public.get_active_season_id() INTO v_season_id;
  IF v_season_id IS NULL OR p_user_id IS NULL THEN RETURN; END IF;
  RETURN QUERY
    WITH totals AS (
      SELECT d.donor_id, sum(d.amount)::bigint AS total_amount,
             dense_rank() OVER (ORDER BY sum(d.amount) DESC) AS rank
      FROM public.donations d WHERE d.donor_id IS NOT NULL AND d.season_id = v_season_id GROUP BY d.donor_id
    )
    SELECT totals.rank::integer, totals.total_amount, v_season_id FROM totals WHERE totals.donor_id = p_user_id;
END;
$$;

-- 에피소드 랭킹
CREATE OR REPLACE FUNCTION public.get_episode_rankings(p_episode_id bigint, p_limit integer DEFAULT 50)
RETURNS TABLE(rank integer, donor_id uuid, donor_name text, total_amount bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY
    WITH totals AS (
      SELECT d.donor_id, d.donor_name, sum(d.amount)::bigint AS total_amount,
             dense_rank() OVER (ORDER BY sum(d.amount) DESC) AS rank
      FROM public.donations d WHERE d.episode_id = p_episode_id AND d.amount > 0 GROUP BY d.donor_id, d.donor_name
    )
    SELECT totals.rank::integer, totals.donor_id, totals.donor_name, totals.total_amount
    FROM totals WHERE totals.rank <= p_limit ORDER BY totals.rank;
END;
$$;

-- VIP 체크
CREATE OR REPLACE FUNCTION public.is_vip_user(user_id uuid)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_rank integer;
BEGIN
  IF user_id IS NULL THEN RETURN FALSE; END IF;
  IF EXISTS (
    SELECT 1 FROM public.profiles WHERE id = user_id AND role IN ('vip', 'moderator', 'admin', 'superadmin')
  ) THEN RETURN TRUE; END IF;
  SELECT rank INTO v_rank FROM public.get_user_rank(user_id, NULL) LIMIT 1;
  RETURN v_rank IS NOT NULL AND v_rank <= 50;
END;
$$;

-- VIP for episode
CREATE OR REPLACE FUNCTION public.is_vip_for_episode(p_user_id uuid, p_episode_id bigint)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_rank integer;
BEGIN
  IF p_user_id IS NULL THEN RETURN FALSE; END IF;
  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = p_user_id AND role IN ('vip', 'moderator', 'admin', 'superadmin'))
  THEN RETURN TRUE; END IF;
  SELECT rank INTO v_rank FROM (
    WITH totals AS (
      SELECT d.donor_id, dense_rank() OVER (ORDER BY sum(d.amount) DESC) AS rank
      FROM public.donations d WHERE d.episode_id = p_episode_id AND d.amount > 0 GROUP BY d.donor_id
    ) SELECT totals.rank FROM totals WHERE totals.donor_id = p_user_id
  ) sub LIMIT 1;
  RETURN v_rank IS NOT NULL AND v_rank <= 50;
END;
$$;

-- VIP for rank battles
CREATE OR REPLACE FUNCTION public.is_vip_for_rank_battles(p_user_id uuid, p_season_id bigint DEFAULT NULL)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF p_user_id IS NULL THEN RETURN FALSE; END IF;
  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = p_user_id AND role IN ('vip', 'moderator', 'admin', 'superadmin'))
  THEN RETURN TRUE; END IF;
  RETURN public.is_vip_user(p_user_id);
END;
$$;

-- BJ Member 체크
CREATE OR REPLACE FUNCTION public.is_bj_member(user_id uuid)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF user_id IS NULL THEN RETURN FALSE; END IF;
  RETURN EXISTS (
    SELECT 1 FROM public.organization o
    WHERE o.profile_id = user_id AND o.is_active = true
  );
END;
$$;

-- Get BJ Member ID
CREATE OR REPLACE FUNCTION public.get_bj_member_id(user_id uuid)
RETURNS bigint LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE v_member_id bigint;
BEGIN
  IF user_id IS NULL THEN RETURN NULL; END IF;
  SELECT o.id INTO v_member_id FROM public.organization o
  WHERE o.profile_id = user_id AND o.is_active = true LIMIT 1;
  RETURN v_member_id;
END;
$$;

-- 조회수 증가 (atomic)
CREATE OR REPLACE FUNCTION public.increment_post_view_count(p_post_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.posts SET view_count = view_count + 1 WHERE id = p_post_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.increment_notice_view_count(p_notice_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.notices SET view_count = view_count + 1 WHERE id = p_notice_id;
END;
$$;

-- 좋아요 수 증가/감소
CREATE OR REPLACE FUNCTION public.increment_post_like_count(p_post_id bigint, p_delta integer)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE new_count integer;
BEGIN
  UPDATE public.posts SET like_count = GREATEST(0, like_count + p_delta) WHERE id = p_post_id
  RETURNING like_count INTO new_count;
  RETURN COALESCE(new_count, 0);
END;
$$;

-- 댓글 수 증가/감소 (atomic)
CREATE OR REPLACE FUNCTION public.increment_comment_count(p_post_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.posts SET comment_count = comment_count + 1 WHERE id = p_post_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.decrement_comment_count(p_post_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.posts SET comment_count = GREATEST(0, comment_count - 1) WHERE id = p_post_id;
END;
$$;

-- 시즌 랭킹 원자적 교체
CREATE OR REPLACE FUNCTION public.atomic_replace_season_rankings(p_season_id bigint, p_rankings jsonb)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE inserted_count integer;
BEGIN
  DELETE FROM public.season_donation_rankings WHERE season_id = p_season_id;
  INSERT INTO public.season_donation_rankings (season_id, rank, donor_id, donor_name, total_amount, donation_count, top_bj, unit, avatar_url)
  SELECT p_season_id, (r->>'rank')::integer, (r->>'donor_id')::uuid, r->>'donor_name',
         (r->>'total_amount')::bigint, COALESCE((r->>'donation_count')::integer, 0),
         r->>'top_bj', (r->>'unit')::public.org_unit, r->>'avatar_url'
  FROM jsonb_array_elements(p_rankings) AS r;
  GET DIAGNOSTICS inserted_count = ROW_COUNT;
  RETURN inserted_count;
END;
$$;

-- 총 랭킹 원자적 교체
CREATE OR REPLACE FUNCTION public.atomic_replace_total_rankings(p_rankings jsonb)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE inserted_count integer;
BEGIN
  DELETE FROM public.total_donation_rankings;
  INSERT INTO public.total_donation_rankings (rank, donor_id, donor_name, total_amount, donation_count, top_bj, avatar_url)
  SELECT (r->>'rank')::integer, (r->>'donor_id')::uuid, r->>'donor_name',
         (r->>'total_amount')::bigint, COALESCE((r->>'donation_count')::integer, 0),
         r->>'top_bj', r->>'avatar_url'
  FROM jsonb_array_elements(p_rankings) AS r;
  GET DIAGNOSTICS inserted_count = ROW_COUNT;
  RETURN inserted_count;
END;
$$;

-- 활성 시즌 설정
CREATE OR REPLACE FUNCTION public.set_active_season(p_season_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  UPDATE public.seasons SET is_active = false WHERE is_active = true;
  UPDATE public.seasons SET is_active = true WHERE id = p_season_id;
END;
$$;

-- GRANT
GRANT EXECUTE ON FUNCTION public.get_user_rank(uuid, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_rank_active_season(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_episode_rankings(bigint, integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_vip_user(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_vip_for_episode(uuid, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_vip_for_rank_battles(uuid, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_bj_member(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_bj_member_id(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.increment_post_view_count(bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.increment_notice_view_count(bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.increment_post_like_count(bigint, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_comment_count(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.decrement_comment_count(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atomic_replace_season_rankings(bigint, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.atomic_replace_total_rankings(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_active_season(bigint) TO authenticated;

-- =============================================================
-- PART 6: RLS 정책
-- =============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bj_ranks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signature_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notice_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tribute_guestbook ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bj_thank_you_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_personal_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_message_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rank_battle_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.total_donation_rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.season_donation_rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signature_eligibility ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.season_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contribution_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prize_penalties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bj_rank_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bj_episode_performances ENABLE ROW LEVEL SECURITY;

-- profiles
CREATE POLICY "profiles_select" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "profiles_update" ON public.profiles FOR UPDATE
  USING (auth.uid() = id OR public.is_staff(auth.uid()));
CREATE POLICY "profiles_insert" ON public.profiles FOR INSERT
  WITH CHECK (public.is_staff(auth.uid()) OR auth.uid() = id);
CREATE POLICY "profiles_delete" ON public.profiles FOR DELETE
  USING (public.is_staff(auth.uid()));

-- seasons
CREATE POLICY "seasons_select" ON public.seasons FOR SELECT USING (true);
CREATE POLICY "seasons_all" ON public.seasons FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- bj_ranks
CREATE POLICY "bj_ranks_select" ON public.bj_ranks FOR SELECT USING (true);
CREATE POLICY "bj_ranks_all" ON public.bj_ranks FOR ALL
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- organization
CREATE POLICY "org_select" ON public.organization FOR SELECT USING (true);
CREATE POLICY "org_all" ON public.organization FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- episodes
CREATE POLICY "episodes_select" ON public.episodes FOR SELECT USING (true);
CREATE POLICY "episodes_all" ON public.episodes FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- donations
CREATE POLICY "donations_select" ON public.donations FOR SELECT USING (true);
CREATE POLICY "donations_all" ON public.donations FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- vip_rewards
CREATE POLICY "vip_rewards_select" ON public.vip_rewards FOR SELECT USING (true);
CREATE POLICY "vip_rewards_all" ON public.vip_rewards FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- vip_images
CREATE POLICY "vip_images_select" ON public.vip_images FOR SELECT USING (true);
CREATE POLICY "vip_images_all" ON public.vip_images FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- signatures
CREATE POLICY "signatures_select" ON public.signatures FOR SELECT USING (true);
CREATE POLICY "signatures_all" ON public.signatures FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- signature_videos
CREATE POLICY "sig_videos_select" ON public.signature_videos FOR SELECT USING (true);
CREATE POLICY "sig_videos_all" ON public.signature_videos FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- schedules
CREATE POLICY "schedules_select" ON public.schedules FOR SELECT USING (true);
CREATE POLICY "schedules_all" ON public.schedules FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- timeline_events
CREATE POLICY "timeline_select" ON public.timeline_events FOR SELECT USING (true);
CREATE POLICY "timeline_all" ON public.timeline_events FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- notices
CREATE POLICY "notices_select" ON public.notices FOR SELECT USING (true);
CREATE POLICY "notices_all" ON public.notices FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- notice_attachments
CREATE POLICY "notice_attach_select" ON public.notice_attachments FOR SELECT USING (true);
CREATE POLICY "notice_attach_all" ON public.notice_attachments FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- posts
CREATE POLICY "posts_select" ON public.posts FOR SELECT
  USING (is_deleted = false AND (board_type = 'free' OR public.is_vip_user(auth.uid())));
CREATE POLICY "posts_insert" ON public.posts FOR INSERT
  WITH CHECK (auth.uid() = author_id AND (board_type = 'free' OR public.is_vip_user(auth.uid())));
CREATE POLICY "posts_update" ON public.posts FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "posts_delete" ON public.posts FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- comments
CREATE POLICY "comments_select" ON public.comments FOR SELECT USING (is_deleted = false);
CREATE POLICY "comments_insert" ON public.comments FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "comments_update" ON public.comments FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "comments_delete" ON public.comments FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- post_likes
CREATE POLICY "post_likes_select" ON public.post_likes FOR SELECT USING (true);
CREATE POLICY "post_likes_insert" ON public.post_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "post_likes_delete" ON public.post_likes FOR DELETE USING (auth.uid() = user_id);

-- media_content
CREATE POLICY "media_select" ON public.media_content FOR SELECT USING (true);
CREATE POLICY "media_all" ON public.media_content FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- live_status
CREATE POLICY "live_select" ON public.live_status FOR SELECT USING (true);
CREATE POLICY "live_all" ON public.live_status FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- banners
CREATE POLICY "banners_select" ON public.banners FOR SELECT USING (is_active = true);
CREATE POLICY "banners_all" ON public.banners FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- tribute_guestbook
CREATE POLICY "guestbook_select" ON public.tribute_guestbook FOR SELECT
  USING (is_approved = true AND is_deleted = false);
CREATE POLICY "guestbook_insert" ON public.tribute_guestbook FOR INSERT
  WITH CHECK (auth.uid() = author_id);
CREATE POLICY "guestbook_update" ON public.tribute_guestbook FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "guestbook_delete" ON public.tribute_guestbook FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- bj_thank_you_messages
CREATE POLICY "bj_msg_select" ON public.bj_thank_you_messages FOR SELECT
  USING (is_public = true AND is_deleted = false);
CREATE POLICY "bj_msg_select_own" ON public.bj_thank_you_messages FOR SELECT
  USING (public.is_bj_member(auth.uid()));
CREATE POLICY "bj_msg_insert" ON public.bj_thank_you_messages FOR INSERT
  WITH CHECK (public.is_bj_member(auth.uid()));
CREATE POLICY "bj_msg_update" ON public.bj_thank_you_messages FOR UPDATE
  USING (public.is_bj_member(auth.uid()) OR public.is_staff(auth.uid()));
CREATE POLICY "bj_msg_all" ON public.bj_thank_you_messages FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- vip_personal_messages
CREATE POLICY "vip_msg_select_public" ON public.vip_personal_messages FOR SELECT
  USING (is_public = true AND is_deleted = false);
CREATE POLICY "vip_msg_select_own" ON public.vip_personal_messages FOR SELECT
  USING (auth.uid() = vip_profile_id OR auth.uid() = author_id);
CREATE POLICY "vip_msg_insert" ON public.vip_personal_messages FOR INSERT
  WITH CHECK (auth.uid() = author_id AND public.is_vip_user(auth.uid()));
CREATE POLICY "vip_msg_update" ON public.vip_personal_messages FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "vip_msg_all" ON public.vip_personal_messages FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- vip_message_comments
CREATE POLICY "vip_comment_select" ON public.vip_message_comments FOR SELECT USING (is_deleted = false);
CREATE POLICY "vip_comment_insert" ON public.vip_message_comments FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "vip_comment_update" ON public.vip_message_comments FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "vip_comment_delete" ON public.vip_message_comments FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));

-- rank_battle_records
CREATE POLICY "rank_battle_select" ON public.rank_battle_records FOR SELECT USING (true);
CREATE POLICY "rank_battle_all" ON public.rank_battle_records FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- total_donation_rankings
CREATE POLICY "total_rankings_select" ON public.total_donation_rankings FOR SELECT USING (true);
CREATE POLICY "total_rankings_all" ON public.total_donation_rankings FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- season_donation_rankings
CREATE POLICY "season_rankings_select" ON public.season_donation_rankings FOR SELECT USING (true);
CREATE POLICY "season_rankings_all" ON public.season_donation_rankings FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- signature_eligibility
CREATE POLICY "sig_elig_select" ON public.signature_eligibility FOR SELECT USING (true);
CREATE POLICY "sig_elig_all" ON public.signature_eligibility FOR ALL
  USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

-- season_members
CREATE POLICY "season_members_select" ON public.season_members FOR SELECT USING (true);
CREATE POLICY "season_members_all" ON public.season_members FOR ALL
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- contribution_logs
CREATE POLICY "contrib_logs_select" ON public.contribution_logs FOR SELECT
  USING (public.is_admin(auth.uid()));
CREATE POLICY "contrib_logs_all" ON public.contribution_logs FOR ALL
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- prize_penalties
CREATE POLICY "prize_pen_select" ON public.prize_penalties FOR SELECT
  USING (public.is_admin(auth.uid()));
CREATE POLICY "prize_pen_all" ON public.prize_penalties FOR ALL
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- bj_rank_history
CREATE POLICY "rank_hist_select" ON public.bj_rank_history FOR SELECT
  USING (public.is_admin(auth.uid()));
CREATE POLICY "rank_hist_all" ON public.bj_rank_history FOR ALL
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- bj_episode_performances
CREATE POLICY "bj_perf_select" ON public.bj_episode_performances FOR SELECT
  USING (public.is_admin(auth.uid()));
CREATE POLICY "bj_perf_all" ON public.bj_episode_performances FOR ALL
  USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- =============================================================
-- PART 7: 인덱스
-- =============================================================

CREATE INDEX IF NOT EXISTS idx_donations_season ON public.donations(season_id);
CREATE INDEX IF NOT EXISTS idx_donations_donor ON public.donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_amount ON public.donations(amount DESC);
CREATE INDEX IF NOT EXISTS idx_donations_episode ON public.donations(episode_id);
CREATE INDEX IF NOT EXISTS idx_donations_member_name ON public.donations(member_name);
CREATE INDEX IF NOT EXISTS idx_donations_donor_name ON public.donations(donor_name);
CREATE INDEX IF NOT EXISTS idx_donations_donated_at ON public.donations(donated_at);
CREATE INDEX IF NOT EXISTS idx_episodes_source_file ON public.episodes(source_file);
CREATE INDEX IF NOT EXISTS idx_posts_board ON public.posts(board_type);
CREATE INDEX IF NOT EXISTS idx_posts_created ON public.posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post ON public.comments(post_id);
CREATE INDEX IF NOT EXISTS idx_org_unit ON public.organization(unit);
CREATE INDEX IF NOT EXISTS idx_org_parent ON public.organization(parent_id);
CREATE INDEX IF NOT EXISTS idx_notices_pinned ON public.notices(is_pinned DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_timeline_season ON public.timeline_events(season_id, order_index);
CREATE INDEX IF NOT EXISTS idx_schedules_datetime ON public.schedules(start_datetime);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_donation ON public.profiles(total_donation DESC);
CREATE INDEX IF NOT EXISTS idx_guestbook_tribute ON public.tribute_guestbook(tribute_user_id);
CREATE INDEX IF NOT EXISTS idx_guestbook_created ON public.tribute_guestbook(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_banners_active ON public.banners(is_active, display_order) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_signatures_unit ON public.signatures(unit);
CREATE INDEX IF NOT EXISTS idx_signatures_number ON public.signatures(sig_number);
CREATE INDEX IF NOT EXISTS idx_sig_videos_sig ON public.signature_videos(signature_id);
CREATE INDEX IF NOT EXISTS idx_sig_videos_member ON public.signature_videos(member_id);
CREATE INDEX IF NOT EXISTS idx_live_member ON public.live_status(member_id);
CREATE INDEX IF NOT EXISTS idx_live_live ON public.live_status(is_live) WHERE is_live = true;
CREATE INDEX IF NOT EXISTS idx_vip_rewards_season ON public.vip_rewards(season_id);
CREATE INDEX IF NOT EXISTS idx_vip_rewards_rank ON public.vip_rewards(rank);
CREATE INDEX IF NOT EXISTS idx_vip_images_reward ON public.vip_images(reward_id);
CREATE INDEX IF NOT EXISTS idx_media_type ON public.media_content(content_type);
CREATE INDEX IF NOT EXISTS idx_post_likes_post ON public.post_likes(post_id);
CREATE INDEX IF NOT EXISTS idx_post_likes_user ON public.post_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_season_members_season ON public.season_members(season_id);
CREATE INDEX IF NOT EXISTS idx_season_members_member ON public.season_members(member_id);
CREATE INDEX IF NOT EXISTS idx_contrib_logs_member ON public.contribution_logs(bj_member_id);
CREATE INDEX IF NOT EXISTS idx_prize_pen_member ON public.prize_penalties(bj_member_id);
CREATE INDEX IF NOT EXISTS idx_rank_hist_member ON public.bj_rank_history(bj_member_id);
CREATE INDEX IF NOT EXISTS idx_bj_perf_episode ON public.bj_episode_performances(episode_id);

-- =============================================================
-- 완료!
-- 33개 테이블 + 3개 View + 20+ 함수 + 50+ RLS 정책 + 40+ 인덱스
-- =============================================================
